vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        avatars:
            uri_prefix: /uploads/avatars
            upload_destination: "%kernel.project_dir%/public/uploads/avatars"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        videos:
            uri_prefix: /uploads/videos
            upload_destination: "%kernel.project_dir%/public/uploads/videos"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        logos:
            uri_prefix: /uploads/logos
            upload_destination: "%kernel.project_dir%/public/uploads/logos"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        vignettes:
            uri_prefix: /uploads/vignettes
            upload_destination: "%kernel.project_dir%/public/uploads/vignettes"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        backgrounds:
            uri_prefix: /uploads/images/backgrounds
            upload_destination: "%kernel.project_dir%/public/uploads/images/backgrounds"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        actualities:
            uri_prefix: /uploads/actualities
            upload_destination: "%kernel.project_dir%/public/uploads/actualities"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        advertisements:
            uri_prefix: /uploads/images/ads
            upload_destination: "%kernel.project_dir%/public/uploads/images/ads"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
