vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        avatars:
            uri_prefix: /uploads/avatars
            upload_destination: "%kernel.project_dir%/public/uploads/avatars"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        logos:
            uri_prefix: /uploads/logos
            upload_destination: "%kernel.project_dir%/public/uploads/logos"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
